#pragma once

#ifndef RAYTRACER_MAX_RECURSION_DEPTH
#    define RAYTRACER_MAX_RECURSION_DEPTH 8
#endif

#ifndef RAYTRACER_EPSILON
#    define RAYTRACER_EPSILON 0.0075
#endif

#ifndef RAYTRACER_REFLECTIVITY_EPSILON
#    define RAYTRACER_REFLECTIVITY_EPSILON RAYTRACER_EPSILON
#endif

#ifndef MULTITHREAD_WORKERS
#    define MULTITHREAD_WORKERS 12
#endif
